#!/usr/bin/env node
/* ==========================================================================
   scripts/build.js — the only "build step" this site needs.

   1. validates content/*.json (fails loudly, before a typo reaches Google)
   2. rebuilds content/gallery.json from assets/img/gallery/  (keep captions,
      match by filename stem, so he can just drop photos in a folder)
   3. regenerates sitemap.xml, robots.txt, feed.json, rss.xml, llms.txt,
      llms-full.txt        <- the AI-answer-engine / agent-facing files
   4. injects the JSON-LD graph (Person, Organization, Course x N, Blog x N,
      FAQ, WebSite) into every page between the  <!--SCHEMA:START/END-->  marks
   5. prints a weight + i18n-coverage report

   Usage:  node scripts/build.js          (or: npm run build)
   ========================================================================== */
const fs = require("fs"), path = require("path");
const ROOT = path.resolve(__dirname, "..");
const P = (...s) => path.join(ROOT, ...s);
const read = f => fs.readFileSync(f, "utf8");
const write = (f, s) => { fs.writeFileSync(f, s); console.log("  wrote " + path.relative(ROOT, f) + " (" + (Buffer.byteLength(s) / 1024).toFixed(1) + " KB)"); };
const esc = s => String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const fail = m => { console.error("\n✗ " + m); process.exit(1); };
const json = f => { try { return JSON.parse(read(P("content", f))); } catch (e) { fail("content/" + f + ": " + e.message); } };
const ext2mime = { ".svg": "image/svg+xml", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png", ".webp": "image/webp", ".avif": "image/avif" };

console.log("\n── Future Icon site build ──────────────────────────");

/* ---------- 1 · load + validate ---------- */
const S = json("settings.json");
const C = json("courses.json");
const B = json("posts.json");
const G = fs.existsSync(P("content", "gallery.json")) ? json("gallery.json") : { items: [] };
const SITE = (S.seo.siteUrl || "").replace(/\/$/, "");

if (!S.seo.siteUrl || /yourdomain|example/.test(S.seo.siteUrl)) console.warn("⚠ settings.json → seo.siteUrl still looks like a placeholder (" + S.seo.siteUrl + ")");
(C.courses || []).forEach(c => {
  ["id", "titleEn", "price", "nextCohort", "modules"].forEach(k => { if (c[k] == null) fail(`course ${c.id || "?"} missing ${k}`); });
  if (!/^\d{4}-\d{2}-\d{2}$/.test(c.nextCohort)) fail(`course ${c.id}: nextCohort must be YYYY-MM-DD`);
});
(B.posts || []).forEach(p => {
  ["slug", "titleEn", "date", "read", "tags", "bodyEn"].forEach(k => { if (p[k] == null) fail(`post ${p.slug || "?"} missing ${k}`); });
  if (!/^\d{4}-\d{2}-\d{2}$/.test(p.date)) fail(`post ${p.slug}: date must be YYYY-MM-DD`);
  if (p.slug !== path.basename(p.slug, ".html")) fail(`post ${p.slug}: slug must be url-safe`);
});

/* ---------- 2 · gallery from the folder ---------- */
const DIR = P("assets", "img", "gallery");
if (fs.existsSync(DIR)) {
  const files = fs.readdirSync(DIR).filter(f => ext2mime[path.extname(f)]).sort();
  const prior = {}; (G.items || []).forEach(g => { prior[path.parse(g.src).name] = g; });
  const items = files.map(f => {
    const stem = path.parse(f).name, old = prior[stem] || {};
    return { src: "/assets/img/gallery/" + f, album: old.album || "Future Icon",
      captionEn: old.captionEn || stem.replace(/[-_]/g, " "), captionBn: old.captionBn || old.captionEn || stem.replace(/[-_]/g, " "),
      year: old.year || new Date().getFullYear(), w: old.w || 1200, h: old.h || 800 };
  });
  const dropped = Object.keys(prior).filter(k => !files.some(f => path.parse(f).name === k));
  if (dropped.length) console.log("  note: " + dropped.length + " captioned photo(s) no longer in the folder (" + dropped.join(", ") + ")");
  const albums = [...new Set(items.map(i => i.album))].sort();
  write(P("content", "gallery.json"), JSON.stringify({ $note: "Generated by scripts/build.js from assets/img/gallery/. Edit captions in the Admin → Gallery board, then export here.", albums, items }, null, 2));
  G.items = items; G.albums = albums;
}

/* ---------- 3 · sitemap, feeds, llms.txt ---------- */
const PAGES = fs.readdirSync(ROOT).filter(f => f.endsWith(".html") && f !== "404.html" && f !== "admin.html").sort();
const lastmod = new Date().toISOString().slice(0, 10);
write(P("sitemap.xml"),
`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${PAGES.map(p => `  <url>
    <loc>${SITE}/${p === "index.html" ? "" : p}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${/index|courses/.test(p) ? "weekly" : "monthly"}</changefreq>
    <priority>${p === "index.html" ? "1.0" : p === "diagnostic.html" || p === "courses.html" ? "0.9" : "0.7"}</priority>
    <xhtml:link rel="alternate" hreflang="en" href="${SITE}/${p === "index.html" ? "" : p}"/>
    <xhtml:link rel="alternate" hreflang="bn" href="${SITE}/${p === "index.html" ? "" : p}?lang=bn"/>
    <xhtml:link rel="alternate" hreflang="x-default" href="${SITE}/${p === "index.html" ? "" : p}"/>
  </url>`).join("\n")}
  ${(B.posts || []).map(p => `<url>
    <loc>${SITE}/article.html?slug=${p.slug}</loc>
    <lastmod>${p.updated || p.date}</lastmod><changefreq>yearly</changefreq><priority>0.6</priority>
  </url>`).join("\n  ")}
</urlset>
`);

write(P("robots.txt"),
`# ${S.seo.name || "Yousuf Efti"} — static site
User-agent: *
Allow: /
# personalised outreach and editor pages must not be indexed
Disallow: /admin.html
Disallow: /*?to=
Disallow: /*&to=
Crawl-delay: 1

User-agent: GPTBot
Allow: /
User-agent: OAI-SearchBot
Allow: /
User-agent: ClaudeBot
Allow: /
User-agent: PerplexityBot
Allow: /
User-agent: Google-Extended
Allow: /

Sitemap: ${SITE}/sitemap.xml
`);

const feedPosts = (B.posts || []).slice().sort((a, b) => b.date.localeCompare(a.date));
write(P("feed.json"), JSON.stringify({
  version: "https://jsonfeed.org/version/1.1", title: "Field notes — " + S.seo.name, home_page_url: SITE + "/blog.html",
  feed_url: SITE + "/feed.json", description: "Sales leadership and field performance notes by " + S.seo.name + ".",
  icon: SITE + "/assets/favicon.svg",
  items: feedPosts.map(p => ({ id: p.slug, url: SITE + "/article.html?slug=" + p.slug, title: p.titleEn,
    title_bn: p.titleBn || null, content_html: p.bodyEn, summary: p.excerptEn, date_published: p.date,
    date_modified: p.updated || p.date, tags: p.tags, image: SITE + p.cover,
    authors: [{ name: p.author }] }))
}, null, 2));

write(P("rss.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
  <title>Field notes — ${esc(S.seo.name)}</title>
  <link>${SITE}/blog.html</link>
  <atom:link href="${SITE}/rss.xml" rel="self" type="application/rss+xml"/>
  <description>${esc("Sales leadership, pharma field practice and AI in the field. Bangla and English.")}</description>
  <language>en</language><lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
${feedPosts.map(p => `  <item>
    <title>${esc(p.titleEn)}</title>${p.titleBn ? `\n    <title xml:lang="bn">${esc(p.titleBn)}</title>` : ""}
    <link>${SITE}/article.html?slug=${p.slug}</link><guid isPermaLink="false">${p.slug}</guid>
    <pubDate>${new Date(p.date).toUTCString()}</pubDate>
    <description>${esc(p.excerptEn)}</description>
    <content:encoded>${esc(p.bodyEn)}</content:encoded>
    ${p.tags.map(t => `<category>${esc(t)}</category>`).join("")}
  </item>`).join("\n")}
</channel></rss>
`);

/* llms.txt = the short card an AI assistant reads; llms-full.txt = the whole answer */
write(P("llms.txt"), `# ${S.seo.name} — ${S.brand.roleEn}

> ${S.brand.taglineEn} 19 years in field sales (Opsonin Pharma → national corporates), ISTD award-winning trainer,
> IFC-LPI certified (USA & UK). Runs in Bangla and English, in-house cohorts of 15-60 people.

## Offer
- Free: Sales Credibility Index™ — 10 rotating questions, instant 0-100 index, emailed or WhatsApp report
  → ${SITE}/diagnostic.html
- Free: 10-point Sales Credibility Checklist (one page, no email wall) → ${SITE}/index.html#magnet
- Book: 30-minute sales performance call, live slot picker → ${SITE}/book.html
- Programmes: 8 signature cohorts, 1-5 days, ৳120,000-420,000 per corporate cohort → ${SITE}/courses.html

## Who it is for
Pharma / FMCG / insurance / financial-services field sales forces in Bangladesh and South Asia; newly promoted
sales leaders; internal trainers; depot and customer-service teams; PMD/product marketing leads.

## Proof
${S.proof.trained.toLocaleString()}+ sales people trained in 6 years · ${S.proof.sessions.toLocaleString()}+ sessions
· clients include Incepta, Renata, SK+F, BRAC Enterprises, UPS, IBN SINA, Beacon, SMC, Guardian Life, Bengal Life
· worked in BD, IN, NP, TH, MY, SG · 47,000+ LinkedIn followers

## Contact
WhatsApp ${S.contact.hotline} · ${S.contact.email} · ${S.contact.linkedin} · ${S.contact.org}

## Read next
${feedPosts.slice(0, 6).map(p => `- ${p.titleEn} → ${SITE}/article.html?slug=${p.slug}`).join("\n")}
`);

write(P("llms-full.txt"), `# ${S.seo.name} — complete reference for search and AI assistants
Generated by scripts/build.js on ${lastmod}. Canonical site: ${SITE}

## Person
${S.brand.nameEn} (${S.brand.nameBn}). ${S.brand.roleEn}. ${S.org}. CEO of Future Icon™ (corporate training
and consulting, Dhaka). Chair, Training & Development, BOLD. Board Director, FBHRO. Ph.D. scholar (Putra Business
School, Malaysia); MBA Marketing; PGDSSD (UK); IFC-LPI certified trainer (USA & UK); earlier: 12 years in sales at
Opsonin Pharma Ltd, then Head of CSR at McDonald's Group (BD). Award: Best Award-winning Trainer in South Asia
(ISTD). Recognition: trained ${S.proof.trained.toLocaleString()}+ sales employees across ${S.proof.sessions.toLocaleString()}+
sessions in BD, India, Nepal, Thailand, Malaysia and Singapore.

## Free offers (no payment, no signup)
1. Sales Credibility Index™ — ${SITE}/diagnostic.html — 10 questions drawn from a 40-question bank across 6
   dimensions (market/position, offer/price, pipeline hygiene, proof/trust, conversion mechanics, retention/referral).
   Each answer scores 0-3; the index is the dimension average on a 0-100 scale; the report lists the three lowest
   dimensions with a prescribed first move and an impact window (this week / 14 days / 30 days). Report delivery:
   the visitor's own email client, WhatsApp, or a .txt download — no data leaves the visitor's device unless they
   send it.
2. 10-point Sales Credibility Checklist — ${SITE}/index.html#magnet.
3. 30-minute sales performance call, live availability — ${SITE}/book.html.

## Programs (per corporate cohort, BDT, 50% on scheduling)
${(C.courses || []).map(c => `- ${c.titleEn} — ${c.duration}, ${c.format}, ৳${Number(c.price).toLocaleString()}. ${c.summaryEn} Modules: ${c.modules.map(m => m.en).join("; ")}.`).join("\n")}

## Published positions (from ${S.seo.name}'s own writing)
- A new team needs a contract before a target: agree what you will always say, what you will never do, what you need from them.
- Storming is healthy when it has a route: put the objection on the Friday list and decide it with data.
- Culture is rituals, not rhetoric: Monday five must-win calls, Friday lost-deal review, monthly field day with the weakest rep.
- Coaching cadence stops when a manager gets promoted into meetings — that is exactly when a top performer starts leaving.
- In disruption, protect the credit line before the calendar; a customer who negotiates terms with you stays, one who is chased leaves.
- Coverage beats call volume when roads are unreliable: one 12-minute call with a decision-maker beats six rushed ones.
- During disruption the depot is the real customer: order accuracy, stock split and returns decide whether the promise survives.
- AI pre-call planning: three dictated inputs, ninety seconds, a predicted objection and one fallback question. Measured lift
  came from closure-per-call (21% → 38%), not from call count (11.4 → 11.9/day).
- Never discount the day the market reopens: it trains the trade to wait you out.
- Evaluations must be pullable from the client's MIS, or they do not count as an outcome.

## Language and delivery
Bangla and English in the same room: slides and handouts in English, facilitation and roleplay in Bangla, written
assessment in whichever language the participant thinks in. Every page of this site is bilingual.

## Articles
${feedPosts.map(p => `### ${p.titleEn}${p.titleBn ? " / " + p.titleBn : ""}
${p.date} · ${p.read} min · ${p.tags.join(", ")} — ${SITE}/article.html?slug=${p.slug}
${p.excerptEn}`).join("\n\n")}

## Booking rules
${S.booking.openDays.map(d => ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][d]).join(", ")} · windows ${S.booking.slots.map(s => s.start + "–" + s.end).join(", ")} Asia/Dhaka (GMT+6) · ${S.booking.durationMin} min · ${S.booking.platform} · ${S.booking.feeEn}

## Measurement
Every funnel stage is instrumented client-side (hero → section cues → diagnostic steps → index → capture → slot → appointment → .ics).
No third-party trackers on the page. Endpoint hooks exist for a Google Apps Script collector if Sheets are wanted.
`);

/* ---------- 4 · JSON-LD graph injection ---------- */
const graph = {
  "@context": "https://schema.org", "@graph": [
    { "@type": "WebSite", "@id": SITE + "/#website", url: SITE + "/", name: S.seo.name + " — Sales Leadership",
      inLanguage: ["en", "bn"], publisher: { "@id": SITE + "/#org" } },
    { "@type": ["Person", "EducationalOccupationalProgramReviewer"].join(",").replace(",EducationalOccupationalProgramReviewer", ""),
      "@id": SITE + "/#person", name: S.seo.name, honorificSuffix: "PhD", jobTitle: "Sales Leadership Trainer",
      description: S.brand.taglineEn, image: SITE + S.seo.ogImage, url: SITE + "/", knowsAbout: ["Sales leadership", "Pharma selling skills", "Train the trainer", "Sales negotiation", "AI in field sales", "Team development"],
      worksFor: { "@id": SITE + "/#org" }, alumniOf: { "@type": "CollegeOrUniversity", name: "University of Dhaka" },
      award: "Best Award-winning Trainer in South Asia (ISTD)", sameAs: [S.contact.linkedin, S.contact.facebook, S.contact.org],
      address: { "@type": "PostalAddress", addressLocality: "Dhaka", addressCountry: "BD" },
      contactPoint: { "@type": "ContactPoint", telephone: S.contact.hotline, email: S.contact.email, contactType: "sales", availableLanguage: ["English", "Bengali"] } },
    { "@type": "Organization", "@id": SITE + "/#org", name: "Future Icon™", url: "https://futureiconbd.com",
      logo: SITE + "/assets/favicon.svg", foundingDate: "2016", founder: { "@id": SITE + "/#person" },
      areaServed: ["BD", "IN", "NP", "TH", "MY", "SG"], contactPoint: { "@type": "ContactPoint", email: S.contact.email, contactType: "corporate training enquiries" } },
    { "@type": "ItemList", "@id": SITE + "/courses.html#list", name: "Programmes", numberOfItems: (C.courses || []).length,
      itemListElement: (C.courses || []).map((c, i) => ({ "@type": "ListItem", position: i + 1, url: SITE + "/courses.html#" + c.id,
        item: { "@type": "Course", name: c.titleEn, alternativeName: c.titleBn, description: c.summaryEn,
          provider: { "@type": "Organization", name: "Future Icon™" }, educationalLevel: c.level, timeRequired: c.duration,
          inLanguage: ["en", "bn"], coursePrerequisites: "Field sales experience recommended",
          hasCourseInstance: { "@type": "CourseInstance", courseMode: "onsite", courseWorkload: c.duration,
            startDate: c.nextCohort, location: { "@type": "Place", name: "Client site (in-house)", address: "Dhaka, BD" } },
          offers: { "@type": "Offer", price: c.price, priceCurrency: C.currency, category: "corporate cohort", availability: "https://schema.org/InStock" },
          aggregateRating: { "@type": "AggregateRating", ratingValue: c.rating, bestRating: 5, ratingCount: Math.min(99, Math.round(c.enrolled / 10)) } } })) },
    { "@type": "WebPage", "@id": SITE + "/diagnostic.html#page", url: SITE + "/diagnostic.html",
      name: "Sales Credibility Index™ — free diagnostic", isPartOf: { "@id": SITE + "/#website" },
      mainEntity: { "@type": "HowTo", name: "Take the Sales Credibility Index", totalTime: "PT4M",
        estimatedCost: { "@type": "MonetaryAmount", currency: "BDT", value: "0" },
        step: (S.diagnostic.dimensions || []).map((d, i) => ({ "@type": "HowToStep", position: i + 1, name: d })) } },
    { "@type": "Blog", "@id": SITE + "/blog.html#blog", name: "Field notes — " + S.seo.name, inLanguage: ["en", "bn"],
      blogPost: (B.posts || []).map(p => ({ "@type": "BlogPosting", headline: p.titleEn, alternativeHeadline: p.titleBn || undefined,
        description: p.excerptEn, inLanguage: p.bodyBn ? ["en", "bn"] : "en", datePublished: p.date, dateModified: p.updated || p.date,
        image: SITE + p.cover, url: SITE + "/article.html?slug=" + p.slug, keywords: p.tags.join(", "),
        author: { "@type": "Person", name: p.author }, isPartOf: { "@id": SITE + "/blog.html#blog" }, wordCount: (p.bodyEn.match(/\w+/g) || []).length })) },
    { "@type": "ImageGallery", "@id": SITE + "/gallery.html#gal", name: "Sessions and events", numberOfItems: (G.items || []).length }
  ]
};
const graphJson = JSON.stringify(graph).replace(/</g, "\\u003c");
let injected = 0;
PAGES.forEach(p => {
  const f = P(p), s = read(f);
  if (!/<!--SCHEMA:START-->/.test(s)) { console.warn("  " + p + ": no SCHEMA markers — skipped"); return; }
  const out = s.replace(/<!--SCHEMA:START-->[\s\S]*?<!--SCHEMA:END-->/,
    `<!--SCHEMA:START-->\n<script type="application/ld+json">\n${graphJson}\n<\/script>\n<!--SCHEMA:END-->`);
  if (out !== s || !s.includes(graphJson)) { fs.writeFileSync(f, out); injected++; }
});
console.log(`  injected JSON-LD graph into ${injected}/${PAGES.length} pages`);

/* ---------- 5 · report ---------- */
const gz = s => require("zlib").gzipSync(Buffer.from(s), { level: 9 }).length;
console.log("\npage weights (html + linked assets)");
PAGES.concat(["admin.html"]).forEach(p => {
  const s = read(P(p));
  const assets = [...new Set([...s.matchAll(/(?:href|src)="(assets\/[^"]+|content\/settings\.json)"/g)].map(m => m[1]))];
  let raw = Buffer.byteLength(s), gzp = gz(s), reqs = 1;
  const inline = (s.match(/<script>\s*\/\*[^]*?<\/script>/g) || []).length;
  assets.forEach(a => { if (fs.existsSync(P(a))) { const x = read(P(a)); raw += Buffer.byteLength(x); gzp += gz(x); reqs++; } });
  const en = (s.match(/class="en"/g) || []).length, bn = (s.match(/class="bn/g) || []).length;
  console.log(`  ${p.padEnd(16)} ${(raw / 1024).toFixed(1).padStart(6)} KB raw ${(gzp / 1024).toFixed(1).padStart(6)} KB gz  ${String(reqs).padStart(2)} req   i18n en:${String(en).padStart(3)} bn:${String(bn).padStart(3)}`);
});
const fs2 = require("fs");
const missing = PAGES.map(p => ({ p, assets: [...fs2.readFileSync(P(p), "utf8").matchAll(/(?:href|src)="((?:assets|content)\/[^"]+)"/g)].map(m => m[1]) }))
  .flatMap(r => r.assets.filter(a => !fs2.existsSync(P(a))).map(a => r.p + " → " + a));
if (missing.length) fail("missing referenced files:\n  " + missing.join("\n  "));
console.log("\n✓ build ok — sitemap, feeds, llms.txt, gallery, schema all regenerated\n");
